### ISSUE TITLE
`withBoundary` 生成的组件支持透传 ref ？

### ISSUE THREAD

**Issue by 599316527** [ecomfe/react-suspense-boundary#17]
https://github.com/ecomfe/react-suspense-boundary/blob/8300e7958b00fdc281053c4001952af2c8eb1e3e/src/index.tsx?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L31-L42

预期：

```
withBoundary({forwardRef: true})
```

**Comment by otakustay** [comment]
应该要支持这个能力，默认forward就行，不必加参数了

**Comment by otakustay** [comment]
TS类型写不好，你有经验么，看起来`Props`类型可以推导，但`Ref`类型不确定怎么弄正确

**Comment by 599316527** [comment]
（没啥经验 😷，我平时都不咋写 TS。）

太速度了！👍👍👍

**Comment by otakustay** [comment]
逻辑应该是对的，但不确定类型正确，一路as unknown下去了……
