### ISSUE TITLE
2.0 useGlobalResource 没了？

### ISSUE THREAD

**Issue by 599316527** [ecomfe/react-suspense-boundary#18]
如果自己实现的话，全局cache跟局部cache怎么共存？嵌套 CacheProvider 感觉没法搞。

**Comment by otakustay** [comment]
是的，没有办法，且我看了react 18未来的suspense data fetching也是这个样子，所以暂时没有计划去支持。虽然全局的确实能搞，但未来和官方的方案差距很大也是个麻烦事

**Comment by 599316527** [comment]
开个口子给开发者来搞呢？库本身不提供全局能力。

比如把 CacheProvider 搞成允许开发者自己 create 一个新的 context 出来：

```
// @file: my-global-use-resource
import {createScope} from 'react-suspense-boundary';
export const {CacheProvider, useResource} = createScope();
```

**Comment by otakustay** [comment]
可以搞，你确实有需求的话，我能动手

**Comment by 599316527** [comment]
那就麻烦了 🥰

我这边的需求是：全局的根据 key 展现 help message 的组件 `<Help keyName="abc" />`。
数据从接口读，缓存结果，下次直接展现。
想要用 useResource 来搞，发现没全局缓存了。

**Comment by otakustay** [comment]
试一下`2.2.0`

**Comment by otakustay** [comment]
具体参考：https://github.com/ecomfe/react-suspense-boundary#create-your-own-cache
