### ISSUE TITLE
没有配置renderError时预期是warning

### ISSUE THREAD

**Issue by jacketwpbb** [ecomfe/react-suspense-boundary#20]
https://github.com/ecomfe/react-suspense-boundary/blob/6bcf832af49e4449432c6fdff1b212a48aca1485/src/config.tsx#L15

**Comment by otakustay** [comment]
这个我不打算改，主要有这么几个原因：

1. 改了就是BREAKING CHANGE，会是个大版本
2. 我认为程序应该是有严格性的，一个默认的`renderError`实现无助于实现一个健壮的界面。默认实现如果是`return null`那么出了问题就是界面少一块，这也不是一个应该有的选择
3. 基于2的原因，我认为作为官方实现我没有办法给出一个正确的默认值……
4. 这个问题通过全局塞一个`BoundaryConfigProvider`其实就能解决，业务自己选择默认的`renderError`实现是更合适的
