### ISSUE TITLE
Share resource across boundaries

### ISSUE THREAD

**Issue by otakustay** [ecomfe/react-suspense-boundary#4]
Suppose we have a parent component `A` with 2 children `X` and `Y`, both children requests for the same resource `findValue`.

On the initial setup, `X` and `Y` resides under the same `Boundary` either outside or inside `A` like:

```
- A
    - Boundary
      - X
      - Y
```

Both `X` and `Y` are free to use the same resource via `useResource(findValue, params)` and a singleton response will be cached in `Boundary`, no duplicate requests fires, no extra data synchronization involves.

As long as the app evolves, with the growing complexity in component `Y`, we decide to have a code splitting and a dedicated `Boundary` is introduced to `Y`, results a component tree like:

```
- A
    - Boundary
      - X
      - Boundary
        - Y
```

From this time on, we find `X` and `Y` no longer shares the same cache, they may both request the resource, cache expiration and refresh are not synchronized.

In order to fix this issue, we should enable developers to control which `Boundary` is responsible to a resource, to satisfy this, I'd like to propose a `scope` prop to `Boundary`.

The `scope` prop can be an empty object `{}`, or a unique string if developers decide to name it more human readable. `useResource` then receives a third `options` argument including `scope` to determine the caching `Boundary`, an absence of `scope` option points to the nearest parent `Boundary`.

As internal implement:

1. `Boundary` will no longer manage the cache state inside itself.
2. A global `Map<Scope, Cache>` is established on initialization.
3. Each `Boundary` opens a slot in global map, increase a reference counter on mount.
4. On unmount, `Boundary` decreases the reference counter and may remove this scope if counter is `0`.
5. A everlasting global scope is also provided via `import {globalScope} from 'react-suspense-bounday'`, to enable users cache response globally.

As a side effect of this change, a `useResource` is able to access caches outside its ancestor `Boundary`'s controll, even `X` can reach responses inside `Y`'s parent `Boundary`, this is a potential risk, I'm still inspecting on solutions to this problem.

**Comment by otakustay** [comment]
Recommended code style:

```js
// BoundaryX
export const scope = {};

export default props => <Boundary {...props} scope={scope} />;

// X's parent
import BoundaryX from '@/components/BoundaryX';

<BoundaryX>
    <X />
</BoundaryX>

// X
import {scope} from '@/components/BoundaryX';

const [value] = useResource(findValue, params, {scope});
```

**Comment by otakustay** [comment]
We can also manage to create a "scope chain" in each `Boundary` by receiving outer chain from it's ancestor `Boundary`, concat it with its own scope and pass it via context, by this we are able to check whether a requested scope is inside "scope chain" and throw when not.

**Comment by daxuewen** [comment]
- A
    - Boundary
      - X (**If not used properly, local state may be reset here?**)
      - Boundary
        - Y

**Comment by otakustay** [comment]
All state from `useResource` must be managed in `Boundary`, all other states inside `X` or `Y` are out of the scope of this issue.

The problem is current implement gives on chance that `Y` can access state of `Boundary` above `X`, so when both `X` and `Y` runs `useResource(findValue)`, `findValue` are executed twice.

**Comment by dancerphil** [comment]
Why not:

```diff
// X
-import {scope} from '@/components/BoundaryX';
+import BoundaryX from '@/components/BoundaryX';

-const [value] = useResource(findValue, params, {scope});
+const [value] = useResource(findValue, params, BoundaryX);
```

**Comment by dancerphil** [comment]
This doubles the complexity when it grows.

**Comment by dancerphil** [comment]
Maybe consider manage all state global, while manage loading/error in Boundary

As a possible implement:

- `useResource` checks if promise is pending/resolved/rejected/memoized

	- if resolved/memoized, go continue rendering

	- if pending/reject, throw promise/Error to nearest Boundary

**Comment by otakustay** [comment]
> Why not

I didn't find a solution to use component type in `Boundary` since `BoundaryX` is actually the **parent** of `Boundary`, unless we do:

```js
const BoundaryX = props => <Boundary {...props} scope={BoundaryX} />;
``

**Comment by otakustay** [comment]
> manage all state global, while manage loading/error in Boundary

Then when a global data eixsts, no loading can be displayed, and when global data errors, it always errors unless we expire it.

In mose common cases we want to fetch the latest data when users leaves end re-enters this view, a global cache is difficult to handle this.

**Comment by otakustay** [comment]
This is really difficult, we have to implement a cache object with subscription support in order to notify resource expiration and refresh
